In [1]:
import numpy as np


In [2]:
#1D with numpy

t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)


[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)


Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근


t[0] t[1] t[-1] =  0.0 1.0 6.0


In [6]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.


t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]


In [8]:
# 2) 2D with Numpy

In [9]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [10]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)


Rank  of t:  2
Shape of t:  (4, 3)


In [2]:
import sys
print(sys.executable)


/opt/anaconda3/bin/python


In [3]:
import torch


In [4]:
# 1D with pyTorch

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [5]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape


1
torch.Size([7])
torch.Size([7])


In [6]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱


tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2) 2D with PyTorch


In [7]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape


2
torch.Size([4, 3])


In [12]:
t2 = torch.FloatTensor([[1., 2., 3., 100.],
                       [4., 5., 6., 200.],
                       [7., 8., 9., 300.],
                       [10., 11., 12., 400.]
                      ])

print(t2[2:3, 1])
print(t2[2:, 3:])


tensor([8.])
tensor([[300.],
        [400.]])


In [ ]:
# mean

In [13]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [14]:
print(t.mean())


tensor(2.5000)


In [15]:
print(t.mean(dim=0))


tensor([2., 3.])


In [16]:
print(t.mean(dim=1))


tensor([1.5000, 3.5000])


In [17]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [18]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거


tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [19]:
# 4) 최대(Max)와 아그맥스(ArgMax)

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.max()) # Returns one value: max


tensor(4.)


In [22]:
print(t.max(dim=0)) # Returns two values: max and argmax


torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [25]:
#5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!
import numpy as np

In [27]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)


torch.Size([2, 2, 3])


In [28]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [30]:
ft.view(-1)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [31]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)


tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [36]:
#6) 스퀴즈(Squeeze) - 1인 차원을 제거한다.
ft = torch.FloatTensor([[0], [1], [2]])
ft2 = torch.FloatTensor([[0,1,2]])

In [37]:
print(ft.shape)
print(ft2.shape)

torch.Size([3, 1])
torch.Size([1, 3])


In [38]:
print(ft.squeeze())
print(ft.squeeze().shape)
print(ft2.squeeze())
print(ft2.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])
torch.Size([3])


In [39]:
#7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.
ft = torch.Tensor([0, 1, 2])
print(ft.shape)


torch.Size([3])


In [46]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

print(ft.unsqueeze(1)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
